### ISSUE TITLE
Missed icon

### ISSUE THREAD

**Issue by pdacity** [vooon/hass-myheat#24]
Не отображается иконка интеграции. 

GET https://brands.home-assistant.io/myheat/icon.png 404

![изображение](https://user-images.githubusercontent.com/30793797/216758494-43adf9ad-5c91-480a-8180-3dc7ebc94ce1.png)

И наверное логичней будет использовать такую: mdi:water-boiler

![изображение](https://user-images.githubusercontent.com/30793797/216758591-9fff4a94-448f-4535-ae38-0d0638ad314a.png)

**Comment by vooon** [comment]
Я ее и не загружал.
Иконки интеграций лежат совершенно отдельно, обычно там товарный знак производителя, но сомневаюсь, что MyHeat мне разрешат залить их иконку.

Ну и для начальных версий плагина я даже не думал об этом. Куда важнее поддержать фичи контроллера.

**Comment by vooon** [comment]
![Screenshot 2023-02-04 at 10-34-33 Настройки – Home Assistant (pixelized)](https://user-images.githubusercontent.com/1023568/216760633-d178bc21-fc05-42e2-9a26-da132fa4c807.png)

Вот тут к примеру интеграция с колонкой уже зрелая, а по началу на сколько помню тоже без иконки была.
Возможно важнее опубликовать компонент в реестре HACS, чтоб не приходилось добавлять репу вручную.

**Comment by pdacity** [comment]
В HACS прям годная мысль. А иконка - ну можно взять готовую из библиотеки, примерно корелируется с задачей. В ишью есть название.

**Comment by pdacity** [comment]
Про иконку интеграции. https://community.home-assistant.io/t/custom-component-integration-icon/191726/2

**Comment by vooon** [comment]
Так по прежнему нужно загружать иконку в репу брэндов. `property icon` - это про другое - про иконку уже entity, например switch.

Я вообще задал производителю вопрос по поводу добавления их иконки, но пока молчат.

**Comment by vooon** [comment]
Ну теперь осталось дождаться: https://github.com/home-assistant/brands/pull/5216

**Comment by vooon** [comment]
Готово!
