### ISSUE TITLE
Неверный логин или пароль

### ISSUE THREAD

**Issue by booroondook-eng** [vooon/hass-myheat#31]
Версия интеграции 0.2.0 версия ХА 2023.2.5
Не даёт зарегистрироваться - сообщает "Неверный логин или пароль" 
В качестве пароля пробовал сначала указать ключ API, затем пароль от веб-интерфейса myheat - резальтат один и  тот же.
И логин, и ключ API однозначно верны, ибо использую в ХА "самописную полуинтеграцию" через сенсоры RESTFull, и там они вполне себе работают.

**Comment by booroondook-eng** [comment]
Проблема решилась установкой версии 0.1.0. После успешной регистрации версия была обновлена до 0.2.0

**Comment by vooon** [comment]
Это довольно странно, т.к. разница не велика, в 0.2 я по сути только перевод добавил.

**Comment by booroondook-eng** [comment]
> 

Кстати, в версии 0.2.0 сохранилось упоминание версии 0.1.0 в некоторых местах (в манифесте и еще в каком-то файле, уже не помню).

**Comment by vooon** [comment]
Это пофиксили в #30. Правда после фикса нужно будет делать 0.3...

**Comment by trdeman** [comment]
Та же проблема. Не входит по логину/ключу.
Поставил версию 0.1.0 - она работает. 
Каким образом правильно обновиться до последней версии чтобы продолжало работать?

**Comment by pznamenskii** [comment]
та же проблема

**Comment by sergiogazprom** [comment]
Подтверждаю проблему. Зарегистрировал на сайте MyHeat нового пользователя (с Ником HomeAssistant, что бы в логах MyHeat отличать). Подтвердил адрес эл почты для этого пользователя. Далее из под своего аккаунта в MyHeat (те аккаунта владельца) в настройках доступа даю полный доступ к своему устройству по ключу, т.е. генерирую ключ (его срок жизни 15 минут). Далее в настройках НА пытаюсь добавить интеграцию, ввожу ник пользователя HomeAssistant и сгенерированный на предыдущем шаге ключ - выдает ошибку. Тут же в Myheat перелогиниваюсь с ником HomeAssistant, добавляю устройство по этому же ключу - вижу свое устройство. Т.е. ключ точно рабочий, как и пользователь, но авторизация из под интеграции не проходит.

**Comment by sergiogazprom** [comment]
![Uploading 2024-02-05_14-47-06.png…]()

**Comment by vooon** [comment]
Вроде бы исправил в 0.3.0. Была ошибка где нужен await а где - нет.

**Comment by vooon** [comment]
@trdeman @pznamenskii @sergiogazprom попробуйте сейчас с 0.3.0.

**Comment by vooon** [comment]
Закрываю как исправленную. Я сам несколько раз проверял - пересоздавал подключение - работало.
