### ISSUE TITLE
Перестало работать после обновления HA 2024.2.0

### ISSUE THREAD

**Issue by booroondook-eng** [vooon/hass-myheat#41]
После обновления HA до версии 2024.2.0 интеграция полностью перестала работать. Все ранее имевшиеся объекты стали недоступными. При попытке заново настроить интеграцию выдается ошибка логина-пароля (вернее, не пароля, а API-ключа)

**Comment by vooon** [comment]
Попробую завтра посмотреть.

**Comment by booroondook-eng** [comment]
Если что, вот кусок лога homeassistant:
```
2024-02-09 11:19:15.819 ERROR (MainThread) [custom_components.myheat] Timeout error fetching information from https://my.myheat.net/api/request/ - 
Traceback (most recent call last):
  File "/config/custom_components/myheat/api.py", line 142, in rpc
    response = await self._session.post(url, headers=HEADERS, json=kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 605, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 966, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 622, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/myheat/api.py", line 141, in rpc
    async with async_timeout.timeout(TIMEOUT):
  File "/usr/local/lib/python3.12/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.12/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
TimeoutError

```

**Comment by booroondook-eng** [comment]
И еще кусок:
```
2024-02-09 11:19:37.641 ERROR (MainThread) [homeassistant.components.climate] Error while setting up myheat platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 344, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/myheat/climate.py", line 54, in async_setup_entry
    for env in coordinator.data.get("data", {}).get("envs", [])
               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

```

**Comment by pdacity** [comment]
И еще немного лога при попытке установки версс 2.0 на чистый HASS

`
│Traceback (most recent call last):                                                                                                                                                                                        │
│  File "/usr/src/homeassistant/homeassistant/loader.py", line 847, in get_platform                                                                                                                                        │
│    cache[full_name] = self._import_platform(platform_name)                                                                                                                                                               │
│                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                               │
│  File "/usr/src/homeassistant/homeassistant/loader.py", line 864, in _import_platform                                                                                                                                    │
│    return importlib.import_module(f"{self.pkg_path}.{platform_name}")                                                                                                                                                    │
│           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                    │
│  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module                                                                                                                                       │
│    return _bootstrap._gcd_import(name[level:], package, level)                                                                                                                                                           │
│           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                           │
│  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import                                                                                                                                                         │
│  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load                                                                                                                                                      │
│  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked                                                                                                                                             │
│  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked                                                                                                                                                       │
│  File "<frozen importlib._bootstrap_external>", line 994, in exec_module                                                                                                                                                 │
│  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed                                                                                                                                            │
│  File "/config/custom_components/myheat/config_flow.py", line 29, in <module>                                                                                                                                            │
│    class MhFlowHandler(ConfigFlow, domain=DOMAIN):                                                                                                                                                                       │
│  File "/config/custom_components/myheat/config_flow.py", line 33, in MhFlowHandler                                                                                                                                       │
│    CONNECTION_CLASS = config_entries.CONN_CLASS_CLOUD_POLL                                                                                                                                                               │
│                       ^^^^^^^^^^^^^^                                                                                                                                                                                     │
│NameError: name 'config_entries' is not defined                                                                                                                                                                           │
│2024-02-12 11:18:28.772 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration myheat: Exception importing custom_components.myheat.config_flow
`

**Comment by vooon** [comment]
Уже обновился на 2024.2.2 - версия 0.3.0 продолжает работать.
