### ISSUE TITLE
переключение едениц измерения температуры между F и С

### ISSUE THREAD

**Issue by pdacity** [vooon/hass-myheat#42]
Исчезла возможность выбрать единицы измерения температуры в карточке. Только фаренгейты. 

![изображение](https://github.com/vooon/hass-myheat/assets/30793797/4d8a845f-c51c-4e6b-9485-e3f74ad9e05a)

![изображение](https://github.com/vooon/hass-myheat/assets/30793797/5a3940f5-d37d-4068-95ce-9da18427bb12)

**Comment by vooon** [comment]
Как-то очень странно, захардкожены же: https://github.com/vooon/hass-myheat/blob/master/custom_components/myheat/climate.py#L101

**Comment by vooon** [comment]
А, стоп, а попробуйте переключить язык в интерфейсе.

**Comment by pdacity** [comment]
> А, стоп, а попробуйте переключить язык в интерфейсе.

Переключил язык на русский. Поле в настройках карточки не появилось. 

![изображение](https://github.com/vooon/hass-myheat/assets/30793797/ae27aecb-b51a-454a-a4d3-715c7875ccf9)

**Comment by vooon** [comment]
![Снимок экрана от 2024-02-12 23-45-49](https://github.com/vooon/hass-myheat/assets/1023568/253fd42d-dc78-415e-b0ed-8cc35af6e550)

Настройки - Система - Общие.

**Comment by pdacity** [comment]
Да, точно.. Спасибо. Мое упущение, недодумался..

**Comment by vooon** [comment]
Ну чтож, тогда not a bug :).
