### ISSUE TITLE
binary_sensor.xxx_severity

### ISSUE THREAD

**Issue by booroondook-eng** [vooon/hass-myheat#45]
В новой (0.3.0) версии появился объект "severity", отражающий общее состояние контроллера.
Но почему-то реализован он как "binary_sensor" - то есть, рассчитан на выдачу двух состояний - 1 и 0.
Однако на самом деле значение "severity" может принимать несколько значений, четыре из которых описаны в документации по API:
0 - состояние неизвестно
1 - система работает нормально
32 - предупреждение
64 - критическое состояние системы
По практическому опыту - например, если долгое время нет связи с контроллером или даже с каким-то датчиком, то MyHeat выдает значение severity=64 (критическое состояние системы).

Полагаю, что сенсор "severity" должен быть не бинарным, а обычным, принимающим числовые (целочисленные) значения.

**Comment by vooon** [comment]
Я посчитал, что достаточно сенсора "проблема". К сожалению "мониторинг" у ХА только dead-or-alive, даже варнинг некуда поместить.
Правда я несколько ошибся с условием `>1` - нужно четко `==1`.
Числовое значение можно в аттрибут поместить, к текстовому описанию.

**Comment by vooon** [comment]
Думал еще добавить severity на энвы и инж. Но не нравится как разрастается код. Плюс смотрю что в 2024 часто есть просто список описаний объектов, вместо отдельных классов.

**Comment by vooon** [comment]
Обновил проверку, плюс добавил оригинальное значение:

![Снимок экрана от 2024-02-25 13-29-53](https://github.com/vooon/hass-myheat/assets/1023568/809066dd-4134-41dd-afee-0e96e4ec9ae6)
